import = ["~/.config/alacritty/ayu_dark.toml"]

[cursor.style]
blinking = "Never"
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[shell]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_title = false
opacity = 0.7
title = "alacritty"
