export PATH="$PATH:$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin"
export PATH="$PATH:$HOME/Developer/flutter/bin"
export PATH="$PATH:$HOME/.bin/gradle/6.8/bin/"
export PATH="$PATH:$HOME/.bin/openjdk/15.0.1/bin/"
export PATH="$HOME:$HOME/.bin/git-lfs/2.12.1/bin/"
